### ISSUE TITLE
Directory indexes

### ISSUE THREAD

**Issue by ingydotnet** [yaml/pyyaml.org#1]
We moved this content from an nginx server to github pages. Nginx provides directory content pages. We'll need to generate those now.

For example https://pyyaml.org/download/ is 404 but should be a directory index for https://github.com/yaml/pyyaml.org/tree/master/download

**Comment by ingydotnet** [comment]
@perlpunk See http://pyyaml.resolvent.net/download/ for original html

You should make the new html look like that.

Also if you could add a `make update` in a top level Makefile that would be awesome.

**Comment by perlpunk** [comment]
@ingydotnet Yes, I'll try to make it look like that. But I can't preserve the timestamp

**Comment by ingydotnet** [comment]
@perlpunk No worries on that. it doesn't need to match perfectly.

**Comment by ingydotnet** [comment]
@perlpunk Looks good. Closing this.
