### ISSUE TITLE
“<<:” merge list ERROR

### ISSUE THREAD

**Issue by mr-xuxu** [yaml/pyyaml.org#9]
Why doesn't it support 2 list merge，The final result looks like this
{'w52': [5200, 5220], 'w53': [5300, 5320], 'w52_53': [5200, 5220, 5300, 5300]}

example 1
w52: &w52
  - 5200
  - 5300
w53: &w53
  - 5300
  - 5320
w52_53:
  *w52
  *w53

example 2
w52: &w52
  - 5200
  - 5300
w53: &w53
  - 5300
  - 5320
w52_53:
  <<: *w52
  <<: *w53

**Comment by perlpunk** [comment]
This not the right place for this question.
See https://github.com/yaml/yaml/issues/48
